apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: pipe-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
 - targetId: qsprod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/fryan-argo-free-2/locations/us-central1/clusters/test

# executionConfigs:
# - privatePool:
#    workerPool: "projects/fryan-argo-2/locations/australia-southeast1/workerPools/fryan-cb-pool-4"
#   usages:
#   - DEPLOY
#   - RENDER
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/fryan-argo-free-2/locations/us-central1/clusters/prod

# executionConfigs:
# - privatePool:
#    workerPool: "projects/fryan-argo-2/locations/australia-southeast1/workerPools/fryan-cb-pool-4"
#   usages:
#   - DEPLOY
#   - RENDER