apiVersion: skaffold/v2beta12
kind: Config
build:
  googleCloudBuild:
    projectId: fryan-argo-free-2
  artifacts:
  - image: australia-southeast1-docker.pkg.dev/fryan-argo-free-2/fryan-reg/go-dummy
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
      trustBuilder: true